// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplateorganizations = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/organizations": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve all organizations for the authenticated user with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Get all organizations",
                "operationId": "getOrganizations",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Number of items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OrganizationListAPIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new organization with the provided information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Create a new organization",
                "operationId": "createOrganization",
                "parameters": [
                    {
                        "description": "Organization information",
                        "name": "organization",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateOrganizationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.OrganizationAPIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/organizations/supported-formats": {
            "get": {
                "description": "Get all supported date, time, and amount formats with examples",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Get supported formats",
                "operationId": "getSupportedFormats",
                "responses": {
                    "200": {
                        "description": "Supported formats with examples",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/organizations/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a specific organization by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Get an organization by ID",
                "operationId": "getOrganizationById",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Organization ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OrganizationAPIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an organization's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Update an organization",
                "operationId": "updateOrganization",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Organization ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated organization information",
                        "name": "organization",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateOrganizationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OrganizationAPIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete an organization by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Delete an organization",
                "operationId": "deleteOrganization",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Organization ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OrganizationDeleteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CreateOrganizationRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "additional_payment_methods": {
                    "type": "object"
                },
                "bankaccount_bank": {
                    "type": "string",
                    "example": "Deutsche Bank"
                },
                "bankaccount_bic": {
                    "type": "string",
                    "example": "DEUTDEFF"
                },
                "bankaccount_iban": {
                    "type": "string",
                    "example": "DE89370400440532013000"
                },
                "bankaccount_owner": {
                    "type": "string",
                    "example": "Acme Corporation"
                },
                "city": {
                    "type": "string",
                    "example": "New York"
                },
                "email": {
                    "type": "string",
                    "example": "info@acme.com"
                },
                "invoice_content": {
                    "type": "object"
                },
                "name": {
                    "type": "string",
                    "example": "Acme Corporation"
                },
                "owner_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "owner_title": {
                    "type": "string",
                    "example": "CEO"
                },
                "phone": {
                    "type": "string",
                    "example": "+1-555-0123"
                },
                "street_address": {
                    "type": "string",
                    "example": "123 Business St"
                },
                "tax_id": {
                    "type": "string",
                    "example": "TAX123456"
                },
                "tax_rate": {
                    "type": "number",
                    "example": 19
                },
                "tax_ustid": {
                    "type": "string",
                    "example": "DE123456789"
                },
                "unit_price": {
                    "type": "number",
                    "example": 150
                },
                "zip": {
                    "type": "string",
                    "example": "12345"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "details": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "models.OrganizationAPIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.OrganizationResponse"
                },
                "message": {
                    "type": "string",
                    "example": "Organization retrieved successfully"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.OrganizationDeleteResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Organization deleted successfully"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.OrganizationListAPIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.OrganizationResponse"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "message": {
                    "type": "string",
                    "example": "Organizations retrieved successfully"
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "total": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "models.OrganizationResponse": {
            "type": "object",
            "properties": {
                "additional_payment_methods": {
                    "type": "object"
                },
                "amount_format": {
                    "type": "string"
                },
                "bankaccount_bank": {
                    "type": "string"
                },
                "bankaccount_bic": {
                    "type": "string"
                },
                "bankaccount_iban": {
                    "type": "string"
                },
                "bankaccount_owner": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "date_format": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "extra_efforts_billing_mode": {
                    "type": "string"
                },
                "extra_efforts_config": {
                    "type": "object"
                },
                "id": {
                    "type": "integer"
                },
                "invoice_content": {
                    "type": "object"
                },
                "line_item_double_unit_text": {
                    "type": "string"
                },
                "line_item_single_unit_text": {
                    "type": "string"
                },
                "locale": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner_name": {
                    "type": "string"
                },
                "owner_title": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "street_address": {
                    "type": "string"
                },
                "tax_id": {
                    "type": "string"
                },
                "tax_rate": {
                    "type": "number"
                },
                "tax_ustid": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "integer"
                },
                "time_format": {
                    "type": "string"
                },
                "unit_price": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                },
                "zip": {
                    "type": "string"
                }
            }
        },
        "models.UpdateOrganizationRequest": {
            "type": "object",
            "properties": {
                "additional_payment_methods": {
                    "type": "object"
                },
                "bankaccount_bank": {
                    "type": "string",
                    "example": "Deutsche Bank"
                },
                "bankaccount_bic": {
                    "type": "string",
                    "example": "DEUTDEFF"
                },
                "bankaccount_iban": {
                    "type": "string",
                    "example": "DE89370400440532013000"
                },
                "bankaccount_owner": {
                    "type": "string",
                    "example": "Acme Corporation"
                },
                "city": {
                    "type": "string",
                    "example": "New York"
                },
                "email": {
                    "type": "string",
                    "example": "info@acme.com"
                },
                "invoice_content": {
                    "type": "object"
                },
                "name": {
                    "type": "string",
                    "example": "Acme Corporation"
                },
                "owner_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "owner_title": {
                    "type": "string",
                    "example": "CEO"
                },
                "phone": {
                    "type": "string",
                    "example": "+1-555-0123"
                },
                "street_address": {
                    "type": "string",
                    "example": "123 Business St"
                },
                "tax_id": {
                    "type": "string",
                    "example": "TAX123456"
                },
                "tax_rate": {
                    "type": "number",
                    "example": 19
                },
                "tax_ustid": {
                    "type": "string",
                    "example": "DE123456789"
                },
                "unit_price": {
                    "type": "number",
                    "example": 150
                },
                "zip": {
                    "type": "string",
                    "example": "12345"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfoorganizations holds exported Swagger Info so clients can modify it
var SwaggerInfoorganizations = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Organizations API",
	Description:      "Organization management endpoints.",
	InfoInstanceName: "organizations",
	SwaggerTemplate:  docTemplateorganizations,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoorganizations.InstanceName(), SwaggerInfoorganizations)
}
